command! -nargs=* ColorBackup call minieyes#color#backup(<f-args>)
command! -nargs=* ColorRestore call minieyes#color#restore(<f-args>)
command! -nargs=* Config call minieyes#nvim#config(<f-args>)
command! -nargs=* LuaFuncCommand call minieyes#lua#call(<f-args>)
command! -nargs=* Gb call fzf#run(fzf#wrap({'source': readfile($BookMarks), 'center': 10, 'sink': 'cd'}))
command! -nargs=* Gtb call fzf#run(fzf#wrap({'source': readfile($BookMarks), 'center': 10, 'sink': 'tcd'}))
command! -nargs=* ESFiles call fzf#run(fzf#wrap({'source': 'es ' . split(<q-args>, ' ')[0], 'center': 10, 'sink': 'edit'}))
