command! -nargs=* ColorBackup call minieyes#color#backup(<f-args>)
command! -nargs=* ColorRestore call minieyes#color#restore(<f-args>)
command! -nargs=* Config call minieyes#nvim#config(<f-args>)
command! -nargs=* LuaFuncCommand call minieyes#lua#call(<f-args>)
command! -nargs=* Gb lua require'minilua.user'.select_bookmark(require'minilua.user'.goto_project)
command! -nargs=* Gtb lua require'minilua.user'.select_bookmark(require'minilua.user'.open_project)
command! -nargs=* ESFiles lua require'minilua.user'.esfiles()
