-- This file can be loaded by calling `lua require('plugins')` from your init.vim
-- Only required if you have packer configured as `opt`
vim.cmd [[packadd packer.nvim]]
return require('packer').startup(function(use)
    -- use 'codota/tabnine-vim'
    -- use 'garbas/vim-snipmate'
    -- use 'jiangmiao/auto-pairs'
    -- use 'kiteco/vim-plugin'
    -- use 'mnishz/colorscheme-preview.vim'
    -- use 'preservim/nerdtree'
    -- use 'pseewald/vim-anyfold'
    -- use 'vim-scripts/AutoComplPop'
    -- use 'vim-scripts/indentpython.vim'
    -- use 'williamboman/nvim-lsp-installer'
    use 'MarcWeber/vim-addon-mw-utils'
    use 'Shatur/neovim-ayu'
    use 'SirVer/ultisnips'
    use 'Yggdroot/indentLine'
    use 'akinsho/bufferline.nvim'
    use 'akinsho/toggleterm.nvim'
    use 'alvan/vim-closetag'
    use 'beauwilliams/focus.nvim'
    use { "catppuccin/nvim", as = "catppuccin" }
    use 'ctrlpvim/ctrlp.vim'
    use 'dbeecham/ctrlp-commandpalette.vim'
    use {'dracula/vim', as = 'dracula'}
    use 'dstein64/nvim-scrollview'
    use 'easymotion/vim-easymotion'
    use 'embear/vim-localvimrc'
    use 'ervandew/supertab'
    use 'frazrepo/vim-rainbow'
    use 'haringsrob/nvim_context_vt'
    use 'haya14busa/incsearch-easymotion.vim'
    use 'haya14busa/incsearch.vim'
    use 'honza/vim-snippets'
    use 'hrsh7th/cmp-buffer'
    use 'hrsh7th/cmp-cmdline'
    use 'hrsh7th/cmp-nvim-lsp'
    use 'hrsh7th/cmp-path'
    use 'hrsh7th/nvim-cmp'
    use {'iamcco/markdown-preview.nvim', run = 'cd app && yarn install', cmd = 'MarkdownPreview'}
    use 'jeetsukumaran/vim-indentwise'
    use 'junegunn/fzf'
    use 'junegunn/fzf.vim'
    use 'justinmk/vim-sneak'
    use 'kabouzeid/nvim-lspinstall'
    use 'kazhala/close-buffers.nvim'
    use 'kdheepak/lazygit.nvim'
    use 'kyazdani42/nvim-tree.lua'
    use 'kyazdani42/nvim-web-devicons'
    use 'leafgarland/typescript-vim'
    use 'lewis6991/gitsigns.nvim'
    use 'liuchengxu/vim-which-key'
    use 'ludovicchabant/vim-gutentags'
    use 'matbme/JABS.nvim'
    use 'mattn/emmet-vim'
    use 'mg979/vim-visual-multi'
    use 'mhinz/vim-grepper'
    use 'neovim/nvim-lspconfig'
    use 'numToStr/Comment.nvim'
    use 'nvim-lua/completion-nvim'
    use 'nvim-lua/plenary.nvim'
    use { 'nvim-telescope/telescope-fzf-native.nvim',
        run =
            'cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release && '..
            'cmake --build build --config Release && '..
            'cmake --install build --prefix build' }
    use 'nvim-telescope/telescope.nvim'
    use {'nvim-treesitter/nvim-treesitter', run = ':TSUpdate'}
    use 'preservim/nerdcommenter'
    use 'preservim/tagbar'
    use 'quangnguyen30192/cmp-nvim-ultisnips'
    use 'rafi/awesome-vim-colorschemes'
    use 'rcarriga/nvim-notify'
    use 'reedes/vim-thematic'
    use 'skywind3000/vim-quickui'
    use 'tomtom/tlib_vim'
    use 'tpope/vim-fugitive'
    use 'tpope/vim-surround'
    use 'vim-airline/vim-airline'
    use 'vim-airline/vim-airline-themes'
    use 'vim-scripts/RltvNmbr.vim'
    use 'vimwiki/vimwiki'
    use 'wbthomason/packer.nvim'
    use 'windwp/nvim-spectre'
    use 'xiyaowong/nvim-cursorword'
    use 'xolox/vim-colorscheme-switcher'
    use 'xolox/vim-misc'
end)
